blank_issues_enabled: false
contact_links:
  - name: Site oficial
    url: https://againstme.app/
    about: Download, changelog e mais informações
  - name: Email do autor
    url: mailto:joaopedro.ts16@gmail.com
    about: Contato direto para assuntos privados
